services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./outputs:/app/outputs
      - ./models:/app/models
      - ./videos:/app/videos
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  train:
    build: .
    command: /bin/bash -c "echo 'Train container ready' && tail -f /dev/null"
    volumes:
      - ./dataset:/app/dataset
      - ./models:/app/models
      - ./outputs:/app/outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]